sambanova/ai-starter-kit

edgar_qna/edgar_qna_streamlit/edgar_sec_qa.py
edgar_qna/edgar_qna_streamlit/requirements.txt

- Debugged 403 error related to getting SEC data
- Improved prompt to get more information from retrieve documents

Debug component that downloads SEC data. 

---

edgar_qna/requirements.txt
enterprise_knowledge_retriever/README.md
enterprise_knowledge_retriever/prompts/llama7b-knowledge_retriever-custom_qa_prompt.yaml
enterprise_knowledge_retriever/requirements.txt
enterprise_knowledge_retriever/streamlit/app.py
prompt_engineering/requirements.txt
utils/sambanova_endpoint.py
vectordb/vector_db.py
web_crawled_data_retriever/requirements.txt

streaming in snova langchain wrapper added, and dependencies updated
enterprise knowledge retriever updated, new loading methods and docs updated

multiple improvements to ai-starterkit

---

data_extraction/notebooks/pdf_extraction.ipynb
data_extraction/requirements.txt
data_extraction/requirementsPaddle.txt
post_call_analysis/README.md
post_call_analysis/data/conversations/transcription/Bank Customer Service Call.csv
post_call_analysis/data/documents/example_procedures.txt
post_call_analysis/data/documents/facts/example_facts_bank.txt
post_call_analysis/data/documents/facts/example_facts_emergency.txt
post_call_analysis/notebooks/analysis.ipynb
post_call_analysis/prompts/factual_accuracy_analysis.yaml
post_call_analysis/prompts/nps.yaml
post_call_analysis/prompts/procedures_analysis.yaml
post_call_analysis/prompts/sentiment_analysis.yaml
post_call_analysis/prompts/topic_classification.yaml
post_call_analysis/src/analysis.py
post_call_analysis/streamlit/app.py

feat:  procedures analysis methods
feat: nps prediction method
fix: quality assessment method
fix: other general chains fixes and prom-pt improvements

Post call analysis improvements

---

web_crawled_data_retriever/README.md
web_crawled_data_retriever/docker-compose.yaml
web_crawled_data_retriever/docker/Dockerfile

Added Docker compose and dockerfile scripts. Updated Readme to reflect this.

added Dockerfile

---

CoE_jump_start/README.md

Update README.md add-model-list-link

---

enterprise_knowledge_retriever/README.md

Updated EKR readme with docker deployment demo video

Update README.md with EKR docker video

---

fine_tuning_embeddings/config.yaml
fine_tuning_embeddings/fine_tune_embed_model.py

typo fixes samabaverse -> sambaverse

---

edgar_qna/README.md
fine_tuning_embeddings/README.md
yoda/README.md

Update README for edgar and fine-tune embeddings, minor change to yoga

---

image_search/README.md
post_call_analysis/README.md

Full copy edit, including TOC updates.

Update README files for image_search and post_call_analysis

---

CoE_jump_start/README.md

Copy-edit pass, add logo & TOC, fix some formatting

Update README.md for CoE jumpstart

---

post_call_analysis/README.md

Some restructure and clarification, based on answers to questions

Update README.md for post call analysis

---

yoda/README.md
yoda/data/sambanova_resources_blogs/blog_generative-ai-for-enterprise-and-government.txt
yoda/data/sambanova_resources_blogs/blog_generative-ai-terms.txt
yoda/data/sambastudio/sambastudio_add-datasets.txt
yoda/data/sambastudio/sambastudio_cli-setup.txt

- remove reference to snsdk (after deletion of WIP notebook)
- formatting issues
- We no longer share the google drive link of our dataset - in its place we need clearer instructions of format of dataset.

Readme feedback updates

---

search_assistant/README.md

Copy-edit, simplified structure & headings

Update README.md for search assistant

---

prompt_engineering/README.md

Consistency and copy edit pass

Update README.md for prompt_engineering

---

search_assistant/README.md
web_crawled_data_retriever/README.md

For search, pulled out Retrieval as a separate workflow. 
For web crawler, using same structure as with other kits.

Minor fix in search, full copy-edit for web-crawler

---

fine_tuning_embeddings/README.md

Fix formatting, add details in Setup section, misc. other copyedits.

Finetuning embeddings starter kit README

---

data_extraction/README.md

Update README.md for data instructions

---

enterprise_knowledge_retriever/requirements.txt
enterprise_knowledge_retriever/src/document_retrieval.py
utils/sambanova_endpoint.py

usage of sambanova's langchain integration
fix bug with sambanova embeddings

feat: sambanova's langchain integration usage in entreprise knowledge retriever

---

enterprise_knowledge_retriever/README.md

Minor updates, primarily in the setup/deploy instructions

Update README.md for enterprise knowledge retriever

---

multimodal_knowledge_retriever/README.md

Misc. update partly based on questions I had for/ answers I got from Jorge

Update README.md for multi-modal

---

complex_rag/README.md
complex_rag/notebooks/rag_w_grading.ipynb

Added attribution and reference to the README

LangGraph reference

---

complex_rag/prompts/final_chain_prompt.yaml

Minor prompt change for Llama 3 to provide more detail.

modified final chain prompt to provide more detail

---

benchmarking/README.md
benchmarking/config.yaml
benchmarking/src/llmperf/utils.py
benchmarking/streamlit/app.py

- Superficial, readibility fixes to text files
- utils.py gets significant fixes to how the input request is created: the old logic overcounted the tokens so that the inputs were ~10% shorter than requested
- Basic changes to labels in app.py so that they are correct (it's y vs. x, not x vs. y).

Benchmarking: Doc improvements and bugfix to num input tokens

---

mypy.ini
ruff.toml
settings.json

Cf. this [confluence page](https://sambanova.atlassian.net/wiki/spaces/AIS/pages/1590820987/Python+best+practices) for reference.

Improvement: Add Ruff configuration

---

workshops/ai_engineer_2024/basic_examples/README.md
workshops/ai_engineer_2024/ekr_rag/README.md

update readme for ai engineer 2024 workshop

---

edgar_qna/config.yaml
edgar_qna/requirements.txt
edgar_qna/src/edgar_sec.py
enterprise_knowledge_retriever/config.yaml
enterprise_knowledge_retriever/requirements.txt
enterprise_knowledge_retriever/src/document_retrieval.py
multimodal_knowledge_retriever/config.yaml
multimodal_knowledge_retriever/requirements.txt
multimodal_knowledge_retriever/src/multimodal.py
post_call_analysis/src/analysis.py
search_assistant/config.yaml
search_assistant/src/search_assistant.py
utils/parsing/config.yaml
utils/parsing/sambaparse.py
vectordb/vector_db.py
web_crawled_data_retriever/config.yaml
web_crawled_data_retriever/requirements.txt
web_crawled_data_retriever/src/web_crawling_retriever.py

-EKR now compatible python 3.11
-Old kits now updated and compatible with langchain integration 0.2.6

kits mantainace 

---

benchmarking/README.md

-Added supported LLM models now in each process

Added supported LLM models now in each process

---

multimodal_knowledge_retriever/src/multimodal.py

fix minor bug multimodal knowledge retriever

---

data_extraction/README.md

Add parsing service alternative instructions
Fix typos

Update data extraction README file

---

web_crawled_data_retriever/src/web_crawling_retriever.py

correct select expert parameter name

fix small bug

---

post_call_analysis/config.yaml
post_call_analysis/src/analysis.py
post_call_analysis/tests/pca_test.py
post_call_analysis/tests/test_config.yaml
tests/test_framework.py

- Added unit tests for each of the 8 analysis in post call analysis (PCA) kit in tests/pca_test.py
- Added a tests/test_config.yaml file
- Changed do_sample to False in src/analysis.py (to make answer deterministic)
- Updated test_framework.py

PCA unit test

---

tests/test_framework.py
web_crawled_data_retriever/streamlit/app.py
web_crawled_data_retriever/tests/web_crawling_test.py

Changes:
- Added unit test for web crawling kit
- Updated test_framework.py
- Removed redundant repeated assignments for some of the variables in streamlit/app.py

Unit test for web crawling

---

utils/rag/base_components.py

Fixing agent workflows by adding the log_method import back into utils/rag/base_components

added log_method import from utils

---

utils/parsing/sambaparse.py

Have not added to the EKR streamlit app, but have tested locally.  Please have a quick look.  There is a parameter for kit_dir in the function, which is already defined in the streamlit app.

init commit: Added parse_doc_streamlit function to sampabarse.py

---

README.md

current link is expired/invalid
[Old link](https://discord.gg/54bNAqRw)
[New link](https://discord.gg/YWFrcZKf)

Updated discord invite link

---

benchmarking/src/performance_evaluation.py

- Reverted back to the original way of grouping requests

Reverted back to the original way of grouping requests

---

financial_assistant/README.md
financial_assistant/streamlit/app.py
financial_assistant/streamlit/app_pdf_report.py
financial_assistant/streamlit/utilities_app.py

- Improvements in the cache deletion.
- Improvement of the logic of clear credentials and exit app.
- Some UX improvements in file download.

Improvement/Some UX improvements

---

financial_assistant/config.yaml
financial_assistant/prompts/retrieval_prompts.py
financial_assistant/requirements.txt
financial_assistant/src/llm.py
financial_assistant/src/retrieval.py
financial_assistant/src/tools.py
financial_assistant/src/tools_database.py

- Bugfix in logger error.
- Update requirements.
- Add a QA prompt due to `langchain` upgrade issues with the prompt `hub`.
- Convert the QA prompt to llama 3.1 syntax.

Bugfix/logger + Improvement/upgrade requirements and prompts

---

multimodal_knowledge_retriever/config.yaml
multimodal_knowledge_retriever/notebooks/multimodal_rag.ipynb
multimodal_knowledge_retriever/prompts/llama70b-knowledge_retriever_custom_qa_prompt.yaml
multimodal_knowledge_retriever/prompts/llama70b-table_summary.yaml
multimodal_knowledge_retriever/prompts/llama70b-text_summary.yaml
multimodal_knowledge_retriever/src/multimodal.py
utils/model_wrappers/multimodal_models.py

admit url images
prompts updated to llama3
add model config

multimodal updates

---

.github/workflows/python_checks.yml

Add github actions workflow for `ruff` and `mypy`.

Feature: Github Actions Workflow

---

.gitignore
multimodal_knowledge_retriever/requirements.txt
multimodal_knowledge_retriever/src/multimodal_rag.py
multimodal_knowledge_retriever/streamlit/app.py

reset conversation button
temporal/cached data folders for prod mode

multimodal mantainance

---

google_integration/README.md
google_integration/google_docs.js
google_integration/google_sheets.js
google_integration/walkthrough.js

There are three scripts
1. YouTube walkthrough code, which is an abbreviated version of google_sheets.js features
2. Google sheets integration to create formulas and batch requests
3. Google docs integration to check grammar and rephrase

Google integration base added

---

multimodal_knowledge_retriever/config.yaml
quickstart/multimodal_get_started.ipynb
utils/model_wrappers/multimodal_models.py

adjusted b64 image placeholder, added temporal method to convert url images to b64

updated multimodal wrapper

---

enterprise_knowledge_retriever/tests/ekr_test.py

Sambaparse was changed recently and a lite_mode boolean variable was introduced. This changed wasn't reflected in EKR unit test. Updated the unit test accordingly

update ekr unit test

---

base-requirements.txt

To ensure tests for fine_tuning_embeddings will run.

Bugfix: updated base-requirements.txt to have llama-index

---

quickstart/function_calling_calculate.ipynb

Add simple notebook that shows how to use function calling with Llama 3.1 to evaluate a mathematical expression

Feature: add function calling quickstart notebook

---

function_calling/config.yaml
function_calling/prompts/streamlit_preset_queries.yaml
function_calling/streamlit/app.py

add explanatory message in streamlit app
add preset streamlit queries to config.yaml
set streamlit enabled and default tools from config.yaml
fix minor error preset buttons not populating the chat input

Improvement: Function calling extra configs for streamlit prod mode

---

multimodal_knowledge_retriever/notebooks/1_multimodal_get_started.ipynb
multimodal_knowledge_retriever/streamlit/app.py
quickstart/multimodal_get_started.ipynb

Add 90B model to stremlit model selector
Fix quickstart images not shown in github page
streamlit model selector for both production and not production model

Improvement: mutimodal  kit and quickstart minor changes

---

GETTING_STARTED.md

Update context lengths for supported models in GETTING_STARTED.md

Documentation: Update GETTING_STARTED.md

---

.github/workflows/python_checks.yml

Remove tests from GitHub Actions.

Bugfix: Remove tests from GitHub Actions.

---

enterprise_knowledge_retriever/requirements.txt
enterprise_knowledge_retriever/src/bulkQA.py
enterprise_knowledge_retriever/src/document_retrieval.py
enterprise_knowledge_retriever/streamlit/app.py
enterprise_knowledge_retriever/tests/ekr_test.py

Follow-up to https://github.com/sambanova/ai-starter-kit/pull/374 
Decouple src and UI streamlit code for EKR

Improvement: Decouple src and UI streamlit code for EKR

---

.github/workflows/docker-build-and-test.yml

- Added in PR to run E2E tests at every  pr opened, synchronize, reopened

added in to run at every pr opened, synchronize, reopened

---

benchmarking/src/performance_evaluation.py

Fixed bug when building the prompts for synthetic generation. Optimized generation.

Fixed bug when building the prompts for synthetic generation. Optimized generation.

---

function_calling/streamlit/app.py
function_calling/streamlit/app_description.yaml

- Now is no need to push the set button to start using the kit, the set button will update the tools to use if you modify the tool selector, and max iterations are taken from what is in the selector in each call
- Now we have the execution scratchpad in the main chat container, also we are recording and keeping in each interaction the history of execution scratchpads
- The name of the expander changes from "calling tools to generate a response" and expanded when is processing to "execution scratchpad" and collapsed when the final response is gotten

 Improvement: function calling ui improvements

---

code_copilot/README.md
code_copilot/config.json
code_copilot/config.ts

add SambaNova provider in config.json with default models
add tab autocompletion model
use api generic V2 in config.ts
Update readme

Improvement: code copilot update

---

function_calling/streamlit/app.py

Bugfix: session state variable not found bug in prod mode

Bugfix: session state variable not found bug in prod mode

---

.gitignore
financial_assistant/constants.py
financial_assistant/src/llm.py

Change cache path to save in GCP persistent storage.

Bugfix: Change cache path to save in GCP persistent storage

---

e2e_fine_tuning/notebooks/1_checkpoints.ipynb
e2e_fine_tuning/notebooks/2_datasets.ipynb
e2e_fine_tuning/notebooks/3_fine_tuning.ipynb
e2e_fine_tuning/notebooks/4_deploy.ipynb

fix minor issue with path of example config files

bugfix: e2e finetuning byoc kit

---

multimodal_knowledge_retriever/prompts/llama3-knowledge_retriever_custom_qa_prompt.yaml
multimodal_knowledge_retriever/prompts/multimodal-qa.yaml
multimodal_knowledge_retriever/src/multimodal_rag.py
multimodal_knowledge_retriever/streamlit/app.py
search_assistant/streamlit/app.py

bugfix in getting llm type from config in multimodal and search assistant kit
add padding to extracted images in multimodal kit
fix bug in displayed images when resetting the conversation
minor changes in prompts

bugfix multimodal kit and  sambastudio input credentials

---

benchmarking/src/llmperf/sambanova_client.py
utils/model_wrappers/langchain_chat_models.py
utils/model_wrappers/langchain_llms.py
utils/model_wrappers/multimodal_models.py
utils/model_wrappers/tests/model_wrappers_test.py

update openai api methods in sambastudio wrappers to use 'chat/completions' instead 'openai'
- util langchain chat model
- util langchain llm
- benchmarking model client
- tests model wrappers

Improvement: update model wrappers

---

benchmarking/requirements.txt
benchmarking/src/performance_evaluation.py

- changed persistent files location to speed up process

Improvement: benchmarking persist prompt bins

---

quickstart/README.md

updated model list in quickstart
add QwQ-32B and Llama3.3-70B

documentation: updated model list in quickstart

---

integrations/README.md

First iteration of having an overview for Integrations repo. Will be maintained with upcoming integration content

Create README.md for Integrations Organization

---

financial_assistant/constants.py
financial_assistant/streamlit/app_financial_filings.py
tests/test_framework.py

Bugfix to set the default year back to 2023.
From January 2024, it was pointing to 2024, but the 10K SEC FILINGS for the default stock are not available yet.

Bugfix: Reset the default year to 2023 SEC EDGAR filings

---

enterprise_knowledge_retriever/README.md
enterprise_knowledge_retriever/streamlit/app.py

-fixed issue with chat output format when `$` in model generation
-minor docs changes

Bugfix: EKR chat output format

---

integrations/semantic_kernel/agents_solving_task.ipynb
integrations/semantic_kernel/requirements.txt

- Added notebook example with agents solving a task
- Tested and styling added
- Added requirements file

Feature: Added example with semantic kernel integration

---

benchmarking/src/llmperf/sambanova_client.py

- Added place holder to top_k param as workaround

Workaround for CoE model

---

e2e_fine_tuning/notebooks/3_fine_tuning.ipynb

Add streamlined execution cell to fine-tuning step

improvement: e2e fine-tuning streamlined execution

---

base-requirements.txt
financial_agent_crewai/pyproject.toml
financial_agent_crewai/requirements.txt
financial_assistant/constants.py
financial_assistant/requirements.txt
financial_assistant/src/retrieval.py
financial_assistant/src/tools_yahoo_news.py
financial_assistant/streamlit/app.py
financial_assistant/tests/financial_assistant_test.py
tests/test_framework.py

Update dependencies, update RAG chain, and reinstate tests for the financial assistant.

Bugfix: Update dependencies, update RAG chain, and reinstate tests for the financial assistant

---

prompt_engineering/tests/prompt_engineering_test.py
tests/test_framework.py
utils/tests/api_testing.py

Improvement: changed test model name

---

e2e_fine_tuning/README.md

minor doc update to e2e finetuning readme

Documentation: update README.md

---

benchmarking/src/performance_evaluation.py

- Added max number of workers for Threadpoolexecutors in kit

Improvement: Changed Threadpoolexecutor to support more than default threads

---

quickstart/README.md

add swallow models to model list 
add curl to list models via `models` endpoint

docs: update quickstart model list

---

benchmarking/src/performance_evaluation.py

- Flexibility to change prompts
- Better logic to exxpand prompt
- Timing calculation

Improvement: Flexbility to change prompts

---

benchmarking/src/llmperf/common_metrics.py
benchmarking/src/llmperf/sambanova_client.py
benchmarking/src/performance_evaluation.py

- Added acceptance rate to individual and summary files
- Added server metrics to summary file

Benchmarking: Acceptance rate added

---

benchmarking/benchmarking_studio/real_workload_compiler_results.ipynb
benchmarking/benchmarking_studio/synthetic_compare_different_providers.ipynb
benchmarking/benchmarking_studio/synthetic_compiler_results.ipynb
benchmarking/config.yaml
benchmarking/src/performance_evaluation.py
benchmarking/streamlit/app.py
benchmarking/streamlit/pages/synthetic_performance_eval_st.py
benchmarking/streamlit/streamlit_utils.py
utils/visual/env_utils.py

- Added support to download output files in the Synthetic Perf Eval functionality
- Added uuid in output files
- Changed upper limits to input tokens, output tokens, number of requests and concurrent requests
- Updated notebooks according to new file names
- Added URL for SambaNova Cloud in prod mode

Improvement: Benchmarking with download button in Synthetic Perf Eval

---

multimodal_knowledge_retriever/notebooks/2_multimodal_rag.ipynb

Minor fixes to 2nd multimoad RAG notebook (update paths to prompt templates)

[bugfix] Multimodal RAG notebook

---

benchmarking/README.md
benchmarking/streamlit/pages/chat_performance_st.py

-small changes in readme and aligment with code

Improvement: Updated readme

---

benchmarking/README.md
benchmarking/prompts/custom_prompt_example.jsonl
benchmarking/src/performance_evaluation.py

- Added default prompt for Custom perf eval
- Fixed bug related to chat templates in Custom perf eval process
- Updated readme

Improvement: Benchmarking custom eval with default prompt

---

multimodal_knowledge_retriever/config.yaml
multimodal_knowledge_retriever/notebooks/1_multimodal_get_started.ipynb
multimodal_knowledge_retriever/notebooks/2_multimodal_rag.ipynb
multimodal_knowledge_retriever/requirements.txt
multimodal_knowledge_retriever/streamlit/app.py
quickstart/README.md
quickstart/multimodal_get_started.ipynb
utils/tests/api_testing.py
utils/tests/config.yaml

remove llama 3.2 11B and 90B and replace it to llama 4 maverick in quickstart, multimodal knowledge kit, and tests

improvement: update multimodal models

---

base-requirements.txt
document_comparison/requirements.txt
enterprise_knowledge_retriever/requirements.txt
eval_jumpstart/requirements.txt
function_calling/requirements.txt
multimodal_knowledge_retriever/requirements.txt
post_call_analysis/requirements.txt
search_assistant/requirements.txt
tests/test_framework.py
utils/tests/config.yaml
utils/vectordb/vector_db.py
web_crawled_data_retriever/requirements.txt

- langchain-milvus deactivated
- qwq deactivated because of hitting rate limit

Bug fix: Debugging tests

---

financial_assistant/README.md
financial_assistant/config.yaml
financial_assistant/requirements.txt
financial_assistant/src/llm.py
financial_assistant/src/retrieval.py
financial_assistant/src/tools_database.py
financial_assistant/src/tools_yahoo_news.py
financial_assistant/streamlit/app.py
tests/test_framework.py

Switch to `ChatSambaNovaCloud` and `bind_tools`.

Improvement: Switch to ChatSambaNovaCloud and bind_tools

---

benchmarking/src/chat_performance_evaluation.py
benchmarking/src/evaluator.py
benchmarking/src/llmperf/llmperf_utils.py
benchmarking/src/llmperf/sambanova_client.py
benchmarking/src/performance_evaluation.py
benchmarking/streamlit/app.py
benchmarking/streamlit/pages/chat_performance_st.py
benchmarking/streamlit/pages/custom_performance_eval_st.py
benchmarking/streamlit/pages/real_workload_eval_st.py
benchmarking/streamlit/pages/synthetic_performance_eval_st.py
benchmarking/streamlit/streamlit_utils.py
enterprise_knowledge_retriever/tests/ekr_test.py
ruff.toml
utils/eval/models.py
utils/fine_tuning/src/snsdk_wrapper.py
utils/visual/env_utils.py

- debuged ruff toml
- added some format changes in several files

Bugfix: Ruff toml and format changes

---

benchmarking/benchmarking_scripts/synthetic_performance_eval_script.py
benchmarking/requirements.txt
quickstart/dedicated/Create a Speculative Decoding Pair.ipynb
quickstart/dedicated/README.md

Also included fixes needed for running the `benchmarking/benchmarking_scripts/synthetic_performance_eval_script.py` script without errors.

Improvement: Added notebook to create a SD pair

---

benchmarking/README.md
benchmarking/benchmarking_scripts/synthetic_performance_eval_script.py
benchmarking/run_custom_dataset.sh
benchmarking/run_real_workload_dataset.sh
benchmarking/run_synthetic_dataset.sh
benchmarking/src/evaluator.py
benchmarking/src/llmperf/models.py
benchmarking/src/llmperf/sambanova_client.py
benchmarking/src/performance_evaluation.py

- Added use debugging flag in all CLI functionalities
- Updated README
- Tested with CLI and GUI
- Applied ruff and mypy

Improvement: Added use debugging flag

---

benchmarking/benchmarking_scripts/concurrent_synthetic_performance_eval_script.py

- Contribution from Karen
- Code to run the synthetic perf eval concurrently

Improvement: Benchmarking add concurrent synth perf eval

---

utils/connection_pooling/README.md

- Added a reference to the public repo https://github.sambanovasystems.com/perf/evaluations/tree/main so users can try the connection pooling test

Feature: Add connection pooling test
